spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        myOutput:
          destination: persons
          contentType: application/json
        myInput:
          destination: persons
          contentType: application/json

